//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otel6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Гости.
    /// </summary>
    // *** Start programmer edit section *** (Гости CustomAttributes)

    // *** End programmer edit section *** (Гости CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГостиE", new string[] {
            "КодГостя as \'Код гостя\'",
            "ФИО as \'ФИО\'",
            "Комментарий as \'Комментарий\'"})]
    public class Гости : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодГостя;
        
        private string fФИО;
        
        private string fКомментарий;
        
        private IIS.Otel6.Доступ fДоступ;
        
        // *** Start programmer edit section *** (Гости CustomMembers)

        // *** End programmer edit section *** (Гости CustomMembers)

        
        /// <summary>
        /// КодГостя.
        /// </summary>
        // *** Start programmer edit section *** (Гости.КодГостя CustomAttributes)

        // *** End programmer edit section *** (Гости.КодГостя CustomAttributes)
        public virtual int КодГостя
        {
            get
            {
                // *** Start programmer edit section *** (Гости.КодГостя Get start)

                // *** End programmer edit section *** (Гости.КодГостя Get start)
                int result = this.fКодГостя;
                // *** Start programmer edit section *** (Гости.КодГостя Get end)

                // *** End programmer edit section *** (Гости.КодГостя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гости.КодГостя Set start)

                // *** End programmer edit section *** (Гости.КодГостя Set start)
                this.fКодГостя = value;
                // *** Start programmer edit section *** (Гости.КодГостя Set end)

                // *** End programmer edit section *** (Гости.КодГостя Set end)
            }
        }
        
        /// <summary>
        /// Комментарий.
        /// </summary>
        // *** Start programmer edit section *** (Гости.Комментарий CustomAttributes)

        // *** End programmer edit section *** (Гости.Комментарий CustomAttributes)
        [StrLen(255)]
        public virtual string Комментарий
        {
            get
            {
                // *** Start programmer edit section *** (Гости.Комментарий Get start)

                // *** End programmer edit section *** (Гости.Комментарий Get start)
                string result = this.fКомментарий;
                // *** Start programmer edit section *** (Гости.Комментарий Get end)

                // *** End programmer edit section *** (Гости.Комментарий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гости.Комментарий Set start)

                // *** End programmer edit section *** (Гости.Комментарий Set start)
                this.fКомментарий = value;
                // *** Start programmer edit section *** (Гости.Комментарий Set end)

                // *** End programmer edit section *** (Гости.Комментарий Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Гости.ФИО CustomAttributes)

        // *** End programmer edit section *** (Гости.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Гости.ФИО Get start)

                // *** End programmer edit section *** (Гости.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Гости.ФИО Get end)

                // *** End programmer edit section *** (Гости.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гости.ФИО Set start)

                // *** End programmer edit section *** (Гости.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Гости.ФИО Set end)

                // *** End programmer edit section *** (Гости.ФИО Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Otel6.Доступ.
        /// </summary>
        // *** Start programmer edit section *** (Гости.Доступ CustomAttributes)

        // *** End programmer edit section *** (Гости.Доступ CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Доступ"})]
        public virtual IIS.Otel6.Доступ Доступ
        {
            get
            {
                // *** Start programmer edit section *** (Гости.Доступ Get start)

                // *** End programmer edit section *** (Гости.Доступ Get start)
                IIS.Otel6.Доступ result = this.fДоступ;
                // *** Start programmer edit section *** (Гости.Доступ Get end)

                // *** End programmer edit section *** (Гости.Доступ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Гости.Доступ Set start)

                // *** End programmer edit section *** (Гости.Доступ Set start)
                this.fДоступ = value;
                // *** Start programmer edit section *** (Гости.Доступ Set end)

                // *** End programmer edit section *** (Гости.Доступ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГостиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГостиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГостиE", typeof(IIS.Otel6.Гости));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Гости.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfГости CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfГости CustomAttributes)
    public class DetailArrayOfГости : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Otel6.DetailArrayOfГости members)

        // *** End programmer edit section *** (IIS.Otel6.DetailArrayOfГости members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Гости by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Гости.
        /// </summary>
        public DetailArrayOfГости(IIS.Otel6.Доступ fДоступ) : 
                base(typeof(Гости), ((ICSSoft.STORMNET.DataObject)(fДоступ)))
        {
        }
        
        public IIS.Otel6.Гости this[int index]
        {
            get
            {
                return ((IIS.Otel6.Гости)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Otel6.Гости dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
